---
name: docker-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    uses: liveviewtech/actions/.github/workflows/buildx.yml@v3
    with:
      image-name: uda-service
    secrets: inherit
